name: Test Cpp

on:
  push:
    paths:
      - 'cpp/**'
      - '.github/workflows/cpp.yml'
  pull_request:
    paths:
      - 'cpp/**'
      - '.github/workflows/cpp.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Build
      working-directory: cpp
      run: |
        mkdir build
        cd build
        cmake -G "Unix Makefiles" ..
        cmake --build .

    - name: Test
      working-directory: cpp
      run: |
        cd build
        ./test_bookstore -r console -s
