name: Test Java

on:
  push:
    paths:
      - 'java/**'
      - '.github/workflows/java.yml'
  pull_request:
    paths:
      - 'java/**'
      - '.github/workflows/java.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11, 17, 21]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java-version }}
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('java/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and test
      working-directory: java
      run: mvn -B test
